server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/managementApp
    username: postgres
    password: 6633
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mysecretkey1234567890
  expiration: 86400000 # 24 hours
